name: Deploy Document

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-jsdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm ci

      - name: run
        run: npx jsdoc -r frontend/js

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./js-doc
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
